spring:
  application:
    name: lalafoParser
server:
  port: 9090

lalafo:
  url: https://lalafo.kg/api/search/v3/feed/search




logging:
  level:
    root: info
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    path: logs