spring:
  application:
    name: lalafoParser
server:
  port: 9090

lalafo:
  url: https://lalafo.kg/



logging:
  level:
    root: info
    org:
      springframework:
        security: error
      hibernate:
        stat: error
        type: error
    web: error
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    path: logs